ps1

diff --git a/bin/mkrepo b/bin/mkrepo
--- a/bin/mkrepo
+++ b/bin/mkrepo
@@ -1,28 +1,24 @@
 #!/bin/sh
 
-name="${0##*/}"
+script="${0##*/}"
 
+. ~/lib/functions.sh
+
+# upstream
 GIT_USER="git"
 GIT_HOST="rpi3.local"
 GIT_ROOT="/home/git/repos"
 GIT_UPSTREAM="ssh://${GIT_USER}@${GIT_HOST}/${GIT_ROOT##*/}"
 
-GIT_MYREPO="${HOME}/repos"
-REPO_ROOT="/home/wandsas/repos"
-REPO_OWNER="wandsas"
-REPO_OWNER_NAME="Sascha Wander <wandsas>"
-REPO_OWNER_MAIL="<sascha.wander@onionmail.com>"
+# local
 REPO_BASEDIR="${PWD}"
+REPO="${1}"
 REPO_NAME="${1}.git"
 REPO_DESCRIPTION="${2}"
 
-msg(){ printf "\033[1m=> $@\033[m\n"; }
-info() { printf "\033[1m=> $@\033[m\n"; }
-warn(){ printf "\033[1m\033[33mWARNING: $@\033[m\n"; }
-error() { printf "\033[1m\033[31mERROR: $@\033[m\n"; }
 
 if [ "$#" -lt 2 ] || [ -z "${REPO_DESCRIPTION}" ]; then
-  warn "Usage: ${name} <REPO_NAME> <REPO_DESCIPTION>";
+  warn "Usage: ${script} <REPO_NAME> <REPO_DESCIPTION>";
   exit 17;
 fi
 
@@ -30,67 +26,48 @@ fi
 ssh -t "${GIT_HOST}" test -d "${GIT_ROOT}/${REPO_NAME}"
 STATUS=$?
 if [ ${STATUS} -eq 0 ]; then
-  warn "Repository $REPO_NAME already exist on ${GIT_HOST}"
-  warn "Code: ${STATUS}"
-  exit "${STATUS}"
+  warn "Repo $REPO_NAME already exist on $GIT_HOST error code: $STATUS"
+  exit ${STATUS}
 fi
 
-msg "upstream git root: $GIT_ROOT"
-msg "repo name: $REPO_NAME"
-msg "repo description: $REPO_DESCRIPTION"
+msg "GIT_ROOT=$GIT_ROOT\tGIT_UPSTREAM=$GIT_UPSTREAM\tREPO_BASEDIR=$REPO_BASEDIR"
+msg "REPO=$REPO\tREPO_NAME=$REPO_NAME\tREPO_DESCRIPTION=$REPO_DESCRIPTION"
 
-ssh -t "${GIT_USER}@${GIT_HOST}" "mkdir -p "${GIT_ROOT}/${REPO_NAME}" && git --bare init "${GIT_ROOT}/${REPO_NAME}" && echo ${REPO_DESCRIPTION} > ${GIT_ROOT}/${REPO_NAME}/description"
+ssh -t "${GIT_USER}@${GIT_HOST}" "mkdir -p ${GIT_ROOT}/${REPO_NAME} && git --bare init ${GIT_ROOT}/${REPO_NAME} && echo ${REPO_DESCRIPTION} > ${GIT_ROOT}/${REPO_NAME}/description"
 STATUS="$?"
+
+# failed -> cleanup
 if [ ${STATUS} -ne 0 ]; then
-  error "Creating repo ${REPO_NAME} on ${GIT_HOST} failed."
-  error "Code: ${STATUS}"
-  if [ -d "${GIT_ROOT}/${REPO_NAME}" ]; then
-    rm -Rf "${GIT_ROOT}/${REPO_NAME}"
-    warn "Deleted repo ${REPO_NAME} on remote server ${GIT_HOST}."
-  fi
+  [ -d "${GIT_ROOT}/${REPO}" ] && rm -Rf "${GIT_ROOT}/${REPO}"
+  error "Creating repo $REPO on $GIT_HOST failed with status $STATUS"
   exit ${STATUS}
 else
-  info "Created repo ${REPO_NAME} on ${GIT_HOST} successfully."
+  info "Created repo $REPO on $GIT_HOST successfully"
 fi
 
-# Clone our new repo to tmpdir
-repo="${REPO_NAME%%.*}"
-tmp="$(mktemp -d /tmp/mkrepo.XXXXXX)"
-info "Cloning ${GIT_UPSTREAM}/${REPO_NAME} to ${tmp}/$repo tmpdir"
-git clone "${GIT_UPSTREAM}/${REPO_NAME}" ${tmp}/$repo >/dev/null 2>&1
-STATUS="$?"
-if [ ${STATUS} -ne 0 ]; then
-	error "Exited with status $STATUS"
-  exit ${STATUS}
-fi
-
-# Is local repo still version controlled -> grab remote as upstream to our new repo
+# local repo version controlled -> add remote
 if [ -d "${REPO_BASEDIR}/.git" ]; then
   PREV="$PWD"
   cd "${REPO_BASEDIR}"
-  
-  upstream=$(git remote show origin ${REPO_BASEDIR} | \
-    grep "Fetch URL" | awk '{print $3}')
-  
+  git remote rename origin upstream
+  git remote add origin ssh://git@rpi3.local/repos/${REPO_NAME}
+  git branch --set-upstream-to=origin/master 
   cd "${PREV}"
-  
-  info "Found existing git remote $upstream, try to add it as upstream"
+  info "Found existing repo $REPO"
+  info "Moved remote origin to upstream"
+  info "Added remote origin ${GIT_UPSTREAM}"
 else
   info "No existing git remote found"
-fi
-
-if [ -d "${tmp}/${repo}/.git" ]; then
-  # add remote upstream to our new initialized repo
-  PREV="${PWD}"
-  cd "${tmp}/${repo}"
-  git remote add upstream "${upstream}"
-  git branch --set-upstream-to=origin/master
-  cd "${PREV}"
-  info "Added git remote upstream ${upstream} to ${repo}"
-  # copy ready initialized repo to local basedir
+  info "Cloning new empty repo $REPO"
+  tmp="$(mktemp -d /tmp/${name}.XXXXXX)"
+  git clone "${GIT_UPSTREAM}/${REPO_NAME}" "${tmp}/${REPO}"
+  STATUS="$?"
   cp -Rf "${tmp}/${repo}/.git" "${REPO_BASEDIR}"
   rm -Rf "${tmp}"
   info "Git repo $repo initialized."
 fi
-[ ${STATUS} != 0 ] && warn "Script ${name} exited with error ${STATUS}."
+
+if [ ${STATUS} -ne 0 ]; then
+  warn "Script $script exited with error $STATUS"
+fi
 exit ${STATUS}
